version: '3'
services:
  debug:
    image: phpstorm/php-71-apache-xdebug
    ports:
     - "8082:80"
    volumes:
      - ./www:/var/www/html
    environment:
        XDEBUG_CONFIG: remote_host=127.0.0.1
  sftp:
    image: phpstorm/sftp-server
    ports:
      - "2022:22"
    volumes:
      - /tmp:/home/jetbrains/upload
    command: jetbrains:jetbrains:1001
  mysql:
      image: phpstorm/mysql
      ports:
        - "33056:3306"
      volumes:
        - ./data:/var/lib/mysql
networks:
  default:
    external:
      name: webapps